name: Deploy Cloud Run to GCP

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy-cloud-run-dev:
    name: "Deploy Cloud Run"
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - id: auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: projects/789243475547/locations/global/workloadIdentityPools/github/providers/github
          service_account: gh-actions@pilvi2-jm-sandbox.iam.gserviceaccount.com

      - name: Deploy Cloud Run using the demo image
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: hello-world
          image: us-docker.pkg.dev/cloudrun/container/hello
          region: europe-north1
